### ISSUE TITLE
Need required field validation for inputs. 

### ISSUE THREAD

**Issue by balayokesh** [DIVYA-PAWAR-03/Magic-notes#4]
Able to submit a empty note.  To fix this I recommend adding required field to input fields.
![image](https://github.com/user-attachments/assets/8af5fef5-3554-4e3d-a4b1-4aafe2b50b03)

**Comment by DIVYA-PAWAR-03** [comment]
Make a PR on another branch

**Comment by balayokesh** [comment]
> Make a PR on another branch

Sure, please assign it to me under hactoberfest label
